# -*- coding: utf-8 -*-
"""agents_runner.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d9lq4FkNVSu8t6UohNg4OCTIFzXNu1zh
"""

import os
import json
import tempfile
from typing import List, Dict, Any

USE_NOTEBOOKS = True

NOTEBOOK_PATHS = {
    "threat": "ThreatCollectorAgent.ipynb",
    "vuln": "Vulnerability_Analysis_Agent.ipynb",
    "mitigation": "MitigationAgentCM.ipynb",
    "report": "ReportGenetatorAgent (2).ipynb",
}

def run_threat_collector(uploaded_files: List) -> Dict[str, Any]:
    file_names = [f.name for f in uploaded_files]
    return {
        "status": "ok",
        "files_received": file_names,
        "summary": f"Collected {len(file_names)} file(s)."
    }

def run_vuln_analysis(threat_data: Dict[str, Any]) -> Dict[str, Any]:
    return {
        "status": "ok",
        "input_summary": threat_data.get("summary", ""),
        "vuln_summary": "Example mock: 2 critical, 4 high, 7 medium.",
    }

def run_mitigation_strategist(vuln_results: Dict[str, Any]) -> Dict[str, Any]:
    return {
        "status": "ok",
        "actions": [
            "Patch critical CVEs within 24 hours",
            "Enable MFA for all privileged accounts",
            "Rotate API keys and secrets quarterly",
        ],
    }

def generate_report(threat_data: Dict[str, Any],
                    vuln_results: Dict[str, Any],
                    mitigation_plan: Dict[str, Any],
                    output_pdf_path: str) -> str:
    from reportlab.lib.pagesizes import A4
    from reportlab.pdfgen import canvas

    c = canvas.Canvas(output_pdf_path, pagesize=A4)
    text = c.beginText(40, 800)
    text.textLine("Sybermind Report (MOCK)")
    text.textLine("")
    text.textLine("=== Threat Data ===")
    text.textLine(json.dumps(threat_data)[:900])
    text.textLine("")
    text.textLine("=== Vulnerability Results ===")
    text.textLine(json.dumps(vuln_results)[:900])
    text.textLine("")
    text.textLine("=== Mitigation Plan ===")
    text.textLine(json.dumps(mitigation_plan)[:900])
    c.drawText(text)
    c.showPage()
    c.save()
    return output_pdf_path
