# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N1w3ZdgZje6xqtuYyvQIqBsiartd3pZh
"""

import os
import io
import tempfile

import streamlit as st
from pypdf import PdfReader

from agents_runner import (
    run_threat_collector,
    run_vuln_analysis,
    run_mitigation_strategist,
    generate_report,
)

st.set_page_config(page_title="Cybermind Dashboard", page_icon="🛡️", layout="wide")

st.title("🛡️ Sybermind — AI-powered Cybersecurity Intelligence")
st.caption("Upload your security data → pipeline runs through 4 agents → get final PDF → ask questions about it.")

# --- Sidebar: quick help
with st.sidebar:
    st.subheader("How to use")
    st.markdown("""
    1. Upload one or more files (logs/CSV/JSON).
    2. Click **Run Sybermind Analysis**.
    3. Download the generated **PDF**.
    4. Ask questions about the report in **Q&A**.
    """)
    st.divider()
    st.markdown("**Tip:** Start with a small file to test the flow.")

# --- Upload
st.header("1) Upload your data")
uploaded_files = st.file_uploader(
    "Upload one or more files (any type to start)",
    accept_multiple_files=True
)
run_button = st.button("Run Sybermind Analysis 🚀")

# Session state to keep PDF around
if "report_bytes" not in st.session_state:
    st.session_state.report_bytes = None
if "report_text" not in st.session_state:
    st.session_state.report_text = ""

def extract_pdf_text_from_bytes(pdf_bytes: bytes) -> str:
    with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False) as tmp:
        tmp.write(pdf_bytes)
        tmp.flush()
        path = tmp.name

    try:
        reader = PdfReader(path)
        all_text = ""
        for page in reader.pages:
            try:
                all_text += (page.extract_text() or "") + "\n"
            except Exception:
                pass
        return all_text
    finally:
        try:
            os.remove(path)
        except OSError:
            pass

# --- Pipeline execution
if run_button:
    if not uploaded_files:
        st.error("Please upload at least one file first.")
    else:
        with st.spinner("Running Sybermind pipeline..."):
            # 1. Threat Collector
            st.subheader("🔍 Threat Collector Agent")
            threat_data = run_threat_collector(uploaded_files)
            st.json(threat_data)

            # 2. Vulnerability Analysis
            st.subheader("🧪 Vulnerability Analysis Agent")
            vuln_results = run_vuln_analysis(threat_data)
            st.json(vuln_results)

            # 3. Mitigation Strategist
            st.subheader("🛡️ Mitigation Strategist Agent")
            mitigation_plan = run_mitigation_strategist(vuln_results)
            st.json(mitigation_plan)

            # 4. Report Generator
            st.subheader("📄 Report Generator Agent")
            with tempfile.TemporaryDirectory() as tmpdir:
                output_pdf = os.path.join(tmpdir, "sybermind_report.pdf")
                pdf_path = generate_report(threat_data, vuln_results, mitigation_plan, output_pdf)
                with open(pdf_path, "rb") as f:
                    st.session_state.report_bytes = f.read()

            st.success("Pipeline finished successfully ✅")

            # Extract text for Q&A
            st.session_state.report_text = extract_pdf_text_from_bytes(st.session_state.report_bytes)
            st.info("Report text extracted for Q&A.")

# --- Download + Q&A
st.header("2) Download report & Q&A")
if st.session_state.report_bytes:
    st.download_button(
        label="⬇️ Download Sybermind Report (PDF)",
        data=st.session_state.report_bytes,
        file_name="sybermind_report.pdf",
        mime="application/pdf"
    )

    st.subheader("💬 Q&A about the report")
    question = st.text_input("Ask a question about this report:")
    if question:
        txt = st.session_state.report_text or ""
        if not txt.strip():
            st.warning("No text extracted from the PDF to answer from.")
        else:
            q_tokens = [t.lower() for t in question.split() if len(t) > 2]
            best_para, best_score = "", -1
            for para in txt.split("\n\n"):
                score = sum(para.lower().count(t) for t in q_tokens)
                if score > best_score:
                    best_score, best_para = score, para
            st.markdown("**Answer (from report text):**")
            st.write(best_para if best_para.strip() else "I couldn't find a clear answer in the report.")
else:
    st.info("Run the analysis first to generate the report.")
